# Generated by Django 5.1.2 on 2024-10-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
